CREATE TABLE categories (
    id      INTEGER   NOT NULL PRIMARY KEY,
    name    VARCHAR   NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator INTEGER   NOT NULL REFERENCES users (id),
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
